import { useState } from 'react';
import Container from '../components/Container';
import Card from '../components/Card';
import Button from '../components/Button';
import UploadDropzone from '../components/UploadDropzone';
import ResultCard from '../components/ResultCard';
import ProgressBar from '../components/ProgressBar';

export default function Tool() {
  const [selectedFile, setSelectedFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisProgress, setAnalysisProgress] = useState(0);
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);

  // Sample images for quick testing
  const sampleImages = [
    { id: 1, url: 'https://placehold.co/400x400/4B9CD3/ffffff?text=AI+Sample+1', name: 'ai-sample-1.jpg' },
    { id: 2, url: 'https://placehold.co/400x400/94a3b8/ffffff?text=Human+Sample+2', name: 'human-sample-2.jpg' },
    { id: 3, url: 'https://placehold.co/400x400/4B9CD3/ffffff?text=AI+Sample+3', name: 'ai-generated-3.jpg' },
    { id: 4, url: 'https://placehold.co/400x400/94a3b8/ffffff?text=Human+Sample+4', name: 'photo-4.jpg' },
  ];

  const handleFileSelected = (file) => {
    setSelectedFile(file);
    setResult(null);

    // Create preview URL
    const url = URL.createObjectURL(file);
    setPreviewUrl(url);
  };

  const handleSampleClick = (sample) => {
    setSelectedFile({ name: sample.name, type: 'image/jpeg', isSample: true });
    setPreviewUrl(sample.url);
    setResult(null);
  };

  const analyzeImage = async () => {
    if (!selectedFile) return;

    setIsAnalyzing(true);
    setAnalysisProgress(0);
    setResult(null);

    // Simulate progress
    const progressInterval = setInterval(() => {
      setAnalysisProgress(prev => {
        if (prev >= 95) {
          clearInterval(progressInterval);
          return 95;
        }
        return prev + 5;
      });
    }, 60);

    // Simulate API call with 1.2s delay
    await new Promise(resolve => setTimeout(resolve, 1200));

    clearInterval(progressInterval);
    setAnalysisProgress(100);

    // Mock logic: if filename contains "ai" (case-insensitive), classify as AI
    const fileName = selectedFile.name.toLowerCase();
    const isAI = fileName.includes('ai');

    // Random confidence between 62-94
    const confidence = Math.floor(Math.random() * (94 - 62 + 1)) + 62;

    const mockResult = {
      label: isAI ? 'Likely AI-generated' : 'Likely Human-made',
      confidence,
      explanation: isAI
        ? 'Lorem ipsum dolor sit amet, the image exhibits characteristic artifacts commonly found in synthetic imagery, including subtle frequency patterns and pixel-level inconsistencies typical of generative models.'
        : 'Consectetur adipiscing elit, the image displays natural characteristics consistent with camera sensors, including authentic noise patterns and optical properties that suggest human origin.',
      timestamp: new Date().toLocaleTimeString(),
      thumbnail: previewUrl,
      fileName: selectedFile.name,
    };

    setResult(mockResult);
    setIsAnalyzing(false);

    // Add to history (keep last 3)
    setHistory(prev => [mockResult, ...prev].slice(0, 3));

    // Clean up progress after a moment
    setTimeout(() => setAnalysisProgress(0), 500);
  };

  return (
    <div className="min-h-screen py-12">
      <Container size="narrow">
        <div className="mb-12">
          <h1 className="text-4xl lg:text-5xl font-bold text-gray-900 dark:text-white mb-4">
            AI Image Detection Tool
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-400">
            Upload an image to analyze whether it was generated by AI or created by a human.
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Main Upload and Analysis Area */}
          <div className="lg:col-span-2 space-y-6">
            {!previewUrl ? (
              <UploadDropzone onFileSelected={handleFileSelected} />
            ) : (
              <Card>
                <div className="space-y-4">
                  <div className="relative">
                    <img
                      src={previewUrl}
                      alt="Selected preview"
                      className="w-full rounded-lg max-h-96 object-contain bg-gray-50 dark:bg-gray-900"
                    />
                    <button
                      onClick={() => {
                        setSelectedFile(null);
                        setPreviewUrl(null);
                        setResult(null);
                      }}
                      className="absolute top-2 right-2 p-2 bg-white dark:bg-gray-800 rounded-lg shadow-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors focus:outline-none focus:ring-2 focus:ring-brand"
                      aria-label="Remove image"
                    >
                      <svg className="w-5 h-5 text-gray-700 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  </div>

                  <div className="flex items-center justify-between">
                    <p className="text-sm text-gray-600 dark:text-gray-400 truncate">
                      {selectedFile?.name}
                    </p>
                    <Button
                      onClick={analyzeImage}
                      disabled={isAnalyzing}
                      className="shrink-0"
                    >
                      {isAnalyzing ? 'Analyzing...' : 'Analyze Image'}
                    </Button>
                  </div>

                  {isAnalyzing && (
                    <div>
                      <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">
                        Processing image...
                      </p>
                      <ProgressBar progress={analysisProgress} />
                    </div>
                  )}
                </div>
              </Card>
            )}

            {/* Result Card */}
            {result && !isAnalyzing && (
              <ResultCard
                label={result.label}
                confidence={result.confidence}
                explanation={result.explanation}
              />
            )}

            {/* Disclaimer */}
            <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
              <p className="text-sm text-amber-800 dark:text-amber-200">
                <strong>Disclaimer:</strong> This demo provides a mock result. Actual model integration coming soon.
              </p>
            </div>
          </div>

          {/* Sidebar: Sample Images & History */}
          <div className="space-y-6">
            {/* Sample Images */}
            <Card title="Sample Images">
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
                Click any sample to test the detector
              </p>
              <div className="grid grid-cols-2 gap-3">
                {sampleImages.map((sample) => (
                  <button
                    key={sample.id}
                    onClick={() => handleSampleClick(sample)}
                    className="relative group overflow-hidden rounded-lg border-2 border-gray-200 dark:border-gray-700 hover:border-brand transition-colors focus:outline-none focus:ring-2 focus:ring-brand"
                  >
                    <img
                      src={sample.url}
                      alt={sample.name}
                      className="w-full aspect-square object-cover"
                    />
                    <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors" />
                  </button>
                ))}
              </div>
            </Card>

            {/* History */}
            {history.length > 0 && (
              <Card title="Recent Analysis">
                <div className="space-y-3">
                  {history.map((item, idx) => (
                    <div
                      key={idx}
                      className="flex gap-3 p-3 rounded-lg bg-gray-50 dark:bg-gray-900/50 border border-gray-200 dark:border-gray-700"
                    >
                      <img
                        src={item.thumbnail}
                        alt={item.fileName}
                        className="w-16 h-16 rounded object-cover shrink-0"
                      />
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">
                          {item.fileName}
                        </p>
                        <p className={`text-xs font-semibold ${
                          item.label.includes('AI') ? 'text-brand' : 'text-green-600 dark:text-green-400'
                        }`}>
                          {item.label}
                        </p>
                        <div className="flex items-center gap-2 mt-1">
                          <div className="flex-1 bg-gray-200 dark:bg-gray-700 rounded-full h-1">
                            <div
                              className="bg-brand h-1 rounded-full"
                              style={{ width: `${item.confidence}%` }}
                            />
                          </div>
                          <span className="text-xs text-gray-500 dark:text-gray-400">
                            {item.confidence}%
                          </span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </Card>
            )}
          </div>
        </div>

        {/* Backend Integration Note */}
        <Card className="mt-12 bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800">
          <h3 className="text-lg font-semibold text-blue-900 dark:text-blue-100 mb-2">
            Backend Integration Point
          </h3>
          <p className="text-sm text-blue-800 dark:text-blue-200 mb-3">
            To wire up a real backend API, replace the mock logic in the <code className="bg-blue-100 dark:bg-blue-900 px-1 py-0.5 rounded">analyzeImage</code> function:
          </p>
          <pre className="bg-blue-900 dark:bg-blue-950 text-blue-100 p-4 rounded-lg text-xs overflow-x-auto">
{`// Replace mock logic with:
const formData = new FormData();
formData.append('image', selectedFile);

const response = await fetch('/api/analyze', {
  method: 'POST',
  body: formData,
});

const data = await response.json();
setResult(data);`}
          </pre>
        </Card>
      </Container>
    </div>
  );
}
